name: Copilot Agent Setup

# 授予读取仓库内容的权限以安装依赖
permissions:
  contents: read

jobs:
  # job id 必须严格命名为 'copilot-setup-steps'
  copilot-setup-steps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update apt database
        run: sudo apt-get update

      # 安装 Tauri v2 在 Linux 环境下必须的系统依赖
      # 参考: https://v2.tauri.app/start/prerequisites/#linux
      - name: Install Tauri System Dependencies
        run: |
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      # 安装 Node.js (用于前端 React + Vite)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      # 安装 Rust (用于后端 Tauri Core)
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      # 安装前端依赖 (会自动包含 Tauri CLI)
      - name: Install NPM dependencies
        run: npm install

      # 可选：预编译 Rust 依赖以加速 Agent 后续的构建速度
      # 注意：这可能会增加 Setup 的时间，但能让 Agent 在修改代码后响应更快
      - name: Pre-fetch Rust dependencies
        run: cargo fetch
