name: Copilot Agent Setup

permissions:
  contents: read

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update apt database
        run: sudo apt-get update

      # 关键修复：
      # 1. 显式安装 pkg-config (glib-sys 编译的必须工具)
      # 2. 显式安装 libglib2.0-dev (glib-sys 的头文件来源)
      # 3. 包含了 webkit2gtk-4.1 (Tauri v2 核心)
      - name: Install System Build Dependencies
        run: |
          sudo apt-get install -y \
            pkg-config \
            build-essential \
            libglib2.0-dev \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            libssl-dev \
            curl \
            wget \
            file

      # 验证 pkg-config 是否能找到 glib
      # 这步能帮助你在日志里快速排查问题，如果这步过了，rust 编译基本就没问题
      - name: Verify GLib is discoverable
        run: pkg-config --libs --cflags glib-2.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install NPM dependencies
        run: npm install

      # 只下载 crate 不编译，节省 setup 时间
      # 避免在 setup 阶段进行耗时的编译，只要环境依赖齐了，Agent 后续就能跑通
      - name: Fetch Rust dependencies
        run: cargo fetch
